- name: Collect logstash information
  hosts: 127.0.0.1
  vars:
    aws_profile: quorum
    aws_region: us-west-2
  tasks:
    - name: register logstash ip
      shell: AWS_PROFILE={{ aws_profile }} aws ec2 describe-instances --region={{ aws_region }} --filter 'Name=tag:Role,Values=logstash' | jq -r .Reservations[0].Instances[0].PrivateIpAddress
      register: OUTPUT_LOGSTASH_IP
    - name: Set facts
      set_fact:
        LOGSTASH_IP: "{{ OUTPUT_LOGSTASH_IP.stdout_lines }}"
      delegate_to: '{{ item }}'
      delegate_facts: True
      with_items: "{{ groups['all'] }}"
- name: Setup filebeat
  gather_facts: True
  hosts: all
  vars:
    logstash_ip: "{{ LOGSTASH_IP[0] }}"
  vars_files:
    - ../quorum-consensus/vars/common.yml
  tasks:
    - debug: var=LOGSTASH_IP
    - name: init filebeat config
      template: src=files/etc/filebeat/filebeat.yml.tpl dest=/etc/filebeat/filebeat.yml
      become: yes
    - name: create filebeat config path
      file:
        path: /etc/filebeat/conf.d
        state: directory
      become: yes
    - name: init filebeat input config
      template: src=files/etc/filebeat/conf.d/application.yml.tpl dest=/etc/filebeat/conf.d/application.yml
      become: yes
    - name: restart filebeat
      shell: monit restart filebeat
      become: yes
