- hosts: 127.0.0.1
  connection: local
  vars_files:
    - /home/ubuntu/.prometheus_secret.yml
  tasks:
      - name: init prometheus config
        template: src=prometheus.yml.tpl dest=/home/ubuntu/prometheus/prometheus.yml
        notify: start prometheus
  handlers:
    - name: start prometheus
      shell: sudo bash /etc/init.d/prometheus start
