- hosts: 127.0.0.1
  connection: local
  tasks:
      - name: copy datasources provisioning config
        copy:
          src: provisioning/datasources/prometheus.yml
          dest: /etc/grafana/provisioning/datasources/prometheus.yml
        become: yes
        notify: restart grafana
      - name: create dashboards config path
        file:
          path: /home/ubuntu/grafana/dashboards
          state: directory
      - name: copy dashboards configs
        synchronize:
          src: dashboards
          dest: /home/ubuntu/grafana
      - name: copy dashboards provisioning config
        copy:
          src: provisioning/dashboards/dashboards.yml
          dest: /etc/grafana/provisioning/dashboards/dashboards.yml
        become: yes
        notify: restart grafana
  handlers:
    - name: restart grafana
      shell: monit restart grafana-server
      become: yes
