- name: Display each index's node information
  hosts: 127.0.0.1
  tasks:
    - include_tasks: tasks/debug-node-index.yml
- name: Consensus provisioning
  hosts: all
  vars_files:
    - vars/common.yml
  tasks:
    - include_tasks: tasks/stop-all.yml
    - include_tasks: tasks/init-node-config.yml
    - include_tasks: tasks/init-ibft.yml
      vars:
        NodesNum: 5
    - include_tasks: tasks/start-ibft.yml
      vars:
        PrivacyImpl: tessera
- name: Block other nodes traffic on node-1
  hosts: aws_ec2[0]
  vars_files:
    - vars/common.yml
  tasks:
    - include_tasks: tasks/iptables-clear-all.yml
    - include_tasks: tasks/iptables-block-source.yml
      vars:
        block_ip: "{{ hostvars[groups['aws_ec2'][1]]['private_ip_address'] }}"
    - include_tasks: tasks/iptables-block-source.yml
      vars:
        block_ip: "{{ hostvars[groups['aws_ec2'][2]]['private_ip_address'] }}"
    - include_tasks: tasks/iptables-block-source.yml
      vars:
        block_ip: "{{ hostvars[groups['aws_ec2'][3]]['private_ip_address'] }}"
    - include_tasks: tasks/iptables-block-source.yml
      vars:
        block_ip: "{{ hostvars[groups['aws_ec2'][4]]['private_ip_address'] }}"
