- name: Display each index's node information
  hosts: 127.0.0.1
  tasks:
    - include_tasks: tasks/debug-node-index.yml
- name: Consensus provisioning
  hosts: all
  vars_files:
    - vars/common.yml
  tasks:
    - include_tasks: tasks/consensus-stop-all.yml
    - include_tasks: tasks/consensus-node-config-init.yml
    - include_tasks: tasks/consensus-ibft-init.yml
      vars:
        NodesNum: 5
    - include_tasks: tasks/consensus-ibft-start.yml
      vars:
        PrivacyImpl: tessera
- name: Burst CPU usage for node-1
  hosts: aws_ec2[0]
  tasks:
    - include_tasks: tasks/sysbench-cpu.yml
      vars: 
        max_prime: 20000
        time_sec: 60
        threads: 2
- name: Burst memory usage for node-1
  hosts: aws_ec2[0]
  tasks:
    - include_tasks: tasks/sysbench-memory.yml
      vars:
        block_size: 8K
        total_size: 200G
        operation: write
        access_mode: rnd
        scope: global
        threads: 2
- name: Burst fileio usage for node-1
  hosts: aws_ec2[0]
  tasks:
    - include_tasks: tasks/sysbench-fileio.yml
      vars:
        file_num: 256
        block_size: 8K
        total_size: 1G
        test_mode: rndrw
        rw_ratio: 2
        threads: 2
