- name: Display each index's node information
  hosts: 127.0.0.1
  tasks:
    - include_tasks: tasks/debug-node-index.yml
- name: Consensus provisioning
  hosts: all
  vars_files:
    - vars/common.yml
  tasks:
    - include_tasks: tasks/stop-all.yml
    - include_tasks: tasks/init-node-config.yml
    - include_tasks: tasks/init-ibft.yml
      vars:
        NodesNum: 5
    - include_tasks: tasks/start-ibft.yml
      vars:
        PrivacyImpl: tessera
- name: Burst CPU usage for node-1
  hosts: aws_ec2[0]
  tasks:
    - include_tasks: tasks/sysbench-cpu.yml
      vars: 
        max_prime: 20000
        time_sec: 60
        threads: 2
