- name: Burst memory usage for node-1
  hosts: aws_ec2[0]
  tasks:
    - include_tasks: tasks/sysbench-memory.yml
      vars:
        block_size: 512M
        total_size: 1000G
        operation: write
        access_mode: rnd
        scope: global
        threads: 2
        time_sec: 60
