- name: Burst fileio usage for node-1
  hosts: aws_ec2[0]
  tasks:
    - include_tasks: tasks/sysbench-fileio.yml
      vars:
        file_num: 256
        block_size: 8K
        total_size: 1G
        test_mode: rndrw
        rw_ratio: 2
        threads: 2
        time_sec: 60
