- name: Display each index's node information
  hosts: 127.0.0.1
  tasks:
    - include_tasks: tasks/debug-node-index.yml
- name: Teardown
  hosts: all
  vars_files:
    - vars/common.yml
  tasks:
    - include_tasks: tasks/consensus-stop-all.yml
    - include_tasks: tasks/iptables-clear-all.yml
    - include_tasks: tasks/netem-clear-all.yml
    - include_tasks: tasks/monit-block-exporter-restart.yml
    - include_tasks: tasks/eprius-stop.yml
