---
- name: delete permissioned-nodes.json if existed
  file:
    path: "{{ ProjectDir }}/permissioned-nodes.json"
    state: absent
- name: Init permissioned-nodes.json
  copy:
    src: ../files/permissioned-nodes.json
    dest: "{{ ProjectDir }}/permissioned-nodes.json"
- name: Only keep needed permissioned nodes
  shell: "cd {{ ProjectDir }} && bash remove-permissioned-nodes.sh {{ NodesNum }}"
- name: Update peers IPs
  shell: "cd {{ ProjectDir }} && bash update-permissioned-nodes.sh {{ NodesNum }}"
- name: Init clique
  shell: "cd {{ ProjectDir }} && bash clique-init.sh --numNodes {{ NodesNum }}"
