---
- name: Action for network delays with margin(dalay_time ± margin_time) base on probability
  shell: "tc qdisc {{ action | default('add') }} dev {{ network_interface | default('eth0') }} root netem delay {{ delay_time }} {{ margin_time }} {{ probability }}"
  become: yes
