---
- name: Action for network delays with margin(dalay_time ± margin_time)
  shell: "tc qdisc {{ action | default('add') }} dev {{ network_interface | default('eth0') }} root netem delay {{ delay_time }} {{ margin_time }}"
  become: yes
