---
- name: Action for network delays with margin(dalay_time ± margin_time)
  shell: "tc qdisc {{ action }} dev {{ network_interface }} root netem delay {{ delay_time }} {{ margin_time }}"
  become: yes
