---
tasks:
  - name: delete permissioned-nodes.json if existed
    file:
      path: "/home/ubuntu/quorum-experiment/nodes/permissioned-nodes.json"
      state: absent
  - name: Init permissioned-nodes.json
    copy:
      src: permissioned-nodes.json
      dest: /home/ubuntu/quorum-experiment/nodes/permissioned-nodes.json
  - name: Only keep needed permissioned nodes
    shell: cd /home/ubuntu/quorum-experiment/nodes && bash remove-permissioned-nodes.sh "{{ NodesNum }}"
  - name: Update peers IPs
    shell: cd /home/ubuntu/quorum-experiment/nodes && bash update-permissioned-nodes.sh "{{ NodesNum }}"
  - name: Init raft
    shell: cd /home/ubuntu/quorum-experiment/nodes && bash raft-init.sh --numNodes "{{ NodesNum }}"
  - name: Start raft
    shell: cd /home/ubuntu/quorum-experiment/nodes && bash raft-start.sh "{{ PrivacyImpl }}"
