---
- name: Sysbench - Memory loads 
  shell: "sysbench memory --memory-block-size={{ block_size | default('1K') }} --memory-total-size={{ total_size | default('100G') }} --memory-oper={{ operation | default('write') }} --memory-access-mode={{ access_mode | default('seq') }} --memory-scope={{ scope | default('global') }} --threads={{ threads | default(1) }} --time={{ time_sec | default(0)}} run"
