---
- name: Action for rate control (Limit bandwidth)
  shell: "wondershaper -a {{ network_interface | default('eth0') }} -d {{ network_download_limit | default('4096') }} -u {{ network_upload_limit | default('4096') }}"
  become: yes
